#Answers
ans={'Chandrayaan-2 Mission was launched by which vehicle?':'a',
     'Which among the following country first reached the ‘Dark Side’ of the Moon?':'c',
     'Which country has developed the world-first floating nuclear plant?':'d',
     'Which is the first country, where WhatsApp is launching its ‘WhatsApp Pay’?':'b',
     'Which Indian institution developed an intensive care unit (ICU) grade ventilator under the name of ‘Project Praana’?':'a',
     'Which Technology company has announced a new global skills initiative, to train 25 million people worldwide?':'b',
     'Which Indian institution has partnered with NVIDIA, to establish India’s first ‘NVIDIA AI Technology Centre’?':'c',
     'Which state has recently declared 2020 as the year of Artificial Intelligence (AI) and has signed MoUs with tech firms for AI research?':'b',
     'The first e-waste clinic of India was recently opened in which city?':'c',
     'Which global firm has developed a new Artificial Intelligence (AI) model to protect an endangered whale species?':'c',
     'Which consists of two plates separated by a dielectric and can store a charge?':'b',
     ' "FET" is a type of transistor; Its full name is ________ Effect Transistor.':'a',
     'What are three types of lasers?':'d',
     'What will a UPS be used for in a building?':'a',
     'What does AC and DC stand for in the electrical field?':'a',
     "A given signal's second harmonic is twice the given signal's __________ frequency?": 'c',
     'What does the term PLC stand for?':'c',
     'When measuring the characteristics of a small-signal amplifier, say for a radio receiver, one might be concerned with its "Noise"?':'d',
     'Who created Pretty Good Privacy (PGP)?':'a',
     'After the first photons of light are produced, which process is responsible for amplification of the light?':'b',
     ' What is “Hot Line”?':'d',
     ' Blue is what number on the resistor color code?':'d',
     "A coating of dust on a computer's main circuit boards has this probable consequence":'a',
     'What are the three main search expressions, or operators, recognized by Boolean logic?':'b',
     'What is a GPU?':'b',
     'What is VCM?':'b',
     ' What was the clock speed of the original IBM PC?':'a',
     ' What is NAT?':'a',
     ' What does ICMP stand for?':'d',
     " 'DTP' computer abbreviation usually means?":'b'}


#50-50 lifeline options
ha={'Chandrayaan-2 Mission was launched by which vehicle?':'A. GSLV MkIII  D. PSLV C45',
     'Which among the following country first reached the ‘Dark Side’ of the Moon?':'A. India  C. China ',
     'Which country has developed the world-first floating nuclear plant?':'A. India  D. Russia',
     'Which is the first country, where WhatsApp is launching its ‘WhatsApp Pay’?':' [B] Brazil  [D] South Korea',
     'Which Indian institution developed an intensive care unit (ICU) grade ventilator under the name of ‘Project Praana’?':'[A] Indian Institute of Science (IISc)  [D] IIT- Guwahati',
     'Which Technology company has announced a new global skills initiative, to train 25 million people worldwide?':'[A] Google [B] Microsoft ',
     'Which Indian institution has partnered with NVIDIA, to establish India’s first ‘NVIDIA AI Technology Centre’?':'[B] IISc, Bangalore [C] IIT- Hyderabad ',
     'Which state has recently declared 2020 as the year of Artificial Intelligence (AI) and has signed MoUs with tech firms for AI research?':' [B] Telengana  [D] Assam',
     'The first e-waste clinic of India was recently opened in which city?':' [C] Bhopal [D] Cuttack',
     'Which global firm has developed a new Artificial Intelligence (AI) model to protect an endangered whale species?':'[A] Amazon  [C] Google',
     'Which consists of two plates separated by a dielectric and can store a charge?':'(A) Inductor (B) Capacitor ',
     ' "FET" is a type of transistor; Its full name is ________ Effect Transistor.':'(A) Field  (D) Force',
     'What are three types of lasers?':'(C) Diode, inverted, pointer (D) Gas, solid state, diode',
     'What will a UPS be used for in a building?':'(A) To provide power to essential equipment (C) To carry messages between departments ',
     'What does AC and DC stand for in the electrical field?':'(A) Alternating Current and Direct Current  (D) Atlantic City and District of Columbia',
     "A given signal's second harmonic is twice the given signal's __________ frequency?":' (C) Fundamental (D) Field',
     'What does the term PLC stand for?':'(A) Programmable Lift Computer (C) Programmable Logic Controller ',
     'When measuring the characteristics of a small-signal amplifier, say for a radio receiver, one might be concerned with its "Noise"?':'(A) Fundamental (D) Figure',
     'Who created Pretty Good Privacy (PGP)?':'(A) Phil Zimmermann (B) Tim Berners-Lee ',
     'After the first photons of light are produced, which process is responsible for amplification of the light?':"(A) Blackbody radiation (B) Stimulated emissionillation",
     ' What is “Hot Line”?':'(C) Imaginary line indicating atmospheric pressure (D) A telecommunication link',
     ' Blue is what number on the resistor color code?':'(A) 1  (D) 6',
     "A coating of dust on a computer's main circuit boards has this probable consequence":'(A) Overheating (B) Short circuits',
     'What are the three main search expressions, or operators, recognized by Boolean logic?':' (B) AND, OR, NOT (D) AND, OR, BUT',
     'What is a GPU?':'(B) Graphics Processing Unit (C) Graphical Performance Utility',
     'What is VCM?':'(A) Virtual Connection Manager (B) Virtual Channel Memory',
     ' What was the clock speed of the original IBM PC?':'(A) Less than 5 MHz (B) 10 MHz',
     ' What is NAT?':'(A) Network Address Translation (B) Network Administration Tool',
     ' What does ICMP stand for?':'(A) Internet Connection Modem Protocol (D) Internet Control Message Protocol',
     " 'DTP' computer abbreviation usually means?":'(B) Desk-Top Publishing (C) Data Type Programming'}


#Eliminate one lifeline options
el={'Chandrayaan-2 Mission was launched by which vehicle?':'A. GSLV MkIII B. PSLV C11 C. GSLV F11',
     'Which among the following country first reached the ‘Dark Side’ of the Moon?':'A. India C. China D. Russia',
     'Which country has developed the world-first floating nuclear plant?':'A. India B. China D. Russia',
     'Which is the first country, where WhatsApp is launching its ‘WhatsApp Pay’?':'[A] India [B] Brazil [D] South Korea',
     'Which Indian institution developed an intensive care unit (ICU) grade ventilator under the name of ‘Project Praana’?':'[A] Indian Institute of Science (IISc)  [C] IIT- Delhi [D] IIT- Guwahati',
     'Which Technology company has announced a new global skills initiative, to train 25 million people worldwide?':'[A] Google [B] Microsoft [C] Amazon ',
     'Which Indian institution has partnered with NVIDIA, to establish India’s first ‘NVIDIA AI Technology Centre’?':' [B] IISc, Bangalore [C] IIT- Hyderabad [D] IIT- Kharagpur',
     'Which state has recently declared 2020 as the year of Artificial Intelligence (AI) and has signed MoUs with tech firms for AI research?':'[A] Andhra Pradesh [B] Telengana  [D] Assam',
     'The first e-waste clinic of India was recently opened in which city?':'[A] Lucknow [B] Mumbai [C] Bhopal ',
     'Which global firm has developed a new Artificial Intelligence (AI) model to protect an endangered whale species?':'[B] Microsoft [C] Google [D] Facebook',
     'Which consists of two plates separated by a dielectric and can store a charge?':'(A) Inductor (B) Capacitor (C) Transistor ',
     ' "FET" is a type of transistor; Its full name is ________ Effect Transistor.':'(A) Field (B) Factor  (D) Force',
     'What are three types of lasers?':'(A) Gas, metal vapor, rock (C) Diode, inverted, pointer (D) Gas, solid state, diode',
     'What will a UPS be used for in a building?':'(A) To provide power to essential equipment (C) To carry messages between departments (D) To control lighting and power systems',
     'What does AC and DC stand for in the electrical field?':'(A) Alternating Current and Direct Current  (C) Average Current and Discharged Capacitor (D) Atlantic City and District of Columbia',
     "A given signal's second harmonic is twice the given signal's __________ frequency?":'(A) Fourier (B) Foundation (C) Fundamental ',
     'What does the term PLC stand for?':' (B) Program List Control (C) Programmable Logic Controller (D) Piezo Lamp Connector',
     'When measuring the characteristics of a small-signal amplifier, say for a radio receiver, one might be concerned with its "Noise"?':'(A) Fundamental (C) Force (D) Figure',
     'Who created Pretty Good Privacy (PGP)?':'(A) Phil Zimmermann (B) Tim Berners-Lee (D) Ken Thompson',
     'After the first photons of light are produced, which process is responsible for amplification of the light?':"(A) Blackbody radiation (B) Stimulated emission (C) Planck's radiation ",
     ' What is “Hot Line”?':'(B) Line of control in the battle field (C) Imaginary line indicating atmospheric pressure (D) A telecommunication link',
     ' Blue is what number on the resistor color code?':'(A) 1 (C) 2 (D) 6',
     "A coating of dust on a computer's main circuit boards has this probable consequence":'(A) Overheating (B) Short circuits (C) Slower hard disk',
     'What are the three main search expressions, or operators, recognized by Boolean logic?':'(A) FROM, TO, WHOM (B) AND, OR, NOT (C) SEARCH, KEYWORD, TEXT',
     'What is a GPU?':' (B) Graphics Processing Unit (C) Graphical Performance Utility (D) Graphical Portable Unit',
     'What is VCM?':'(A) Virtual Connection Manager (B) Virtual Channel Memory (C) Voice Controlled Modem',
     ' What was the clock speed of the original IBM PC?':'(A) Less than 5 MHz (B) 10 MHz (C) 8 MHz',
     ' What is NAT?':'(A) Network Address Translation (B) Network Administration Tool (C) Novell Address Transfer',
     ' What does ICMP stand for?':'(A) Internet Connection Modem Protocol (B) Intranet Control Message Program (D) Internet Control Message Protocol',
     " 'DTP' computer abbreviation usually means?":'(A) Digital Transmission Protocol (B) Desk-Top Publishing (C) Data Type Programming'}
